### ISSUE TITLE
performance about segmentation

### ISSUE THREAD

**Issue by annopackage** [allenai/unified-io-2#14]
Hi, the performance of the work is amazing. The segmentation result is decoded by off-the-shelf vqgan decoder. Most part of a single image is background, thus the target tokens between the foreground and background is imbalanced.  In the case, would the transformer tend to learn the bias towards background tokens?

**Comment by jiasenlu** [comment]
Hi Thanks for the question! You are right. In segmentation, most of the token is background. We found the model can do this pretty well, even with an off-the-shelf vqgan decoder. We benchmark the performance of segmentation with GRIT benchmark (https://allenai.org/project/grit/home). One of the tasks from the benchmark is segmentation.
