### ISSUE TITLE
cannot access gs://unified-io-2-us-east/tokenizer/llama_tokenizer.model 

### ISSUE THREAD

**Issue by WorldHellooo** [allenai/unified-io-2#3]
can you please share this file ? I cant access it for unknown reason..

**Comment by xk-huang** [comment]
Just edit the `t5x/examples/unified_io/config.py` :)

>The LLaMa tokenizer also needs to be installed, download the .model file from https://github.com/facebookresearch/llama/tree/main?tab=readme-ov-file and then update t5x/examples/unified_io/config.py so LLAMA_TOKENIZER_PATH points to the download location.

**Comment by chrisc36** [comment]
Yes, we just noticed this issue and updated the repo to fix it. Look at the README to see how to make it work.
