### ISSUE TITLE
Model checkpoints on the 🤗 Hub! 

### ISSUE THREAD

**Issue by Vaibhavs10** [allenai/unified-io-2#5]
Hi there,

I'm VB, I lead the developer advocacy efforts for Audio at Hugging Face. Congratulations on releasing such a brilliant checkpoint.

It'd also be nice to upload the model weights to the hub. This would also increase the model checkpoint's visibility, leading to adoption.

The process to do is quite simple:

1. Under the https://huggingface.co/allenai org create a new model.
2. Upload checkpoints to the repo.
3. Add a model card (similar to GitHub README)

Of course, I am happy to help/ guide you if you have any questions.

Cheers,
VB

**Comment by chrisc36** [comment]
Thanks for the recommendation, we are working on a pytorch version which we plan to upload to huggingface.

**Comment by akashicMarga** [comment]
@chrisc36 any idea when pytorch version will be out? Eagerly waithing to try this out. Amazing work!!!

Tried running the existing code but getting errors. seems the installation is not working properly.

**Comment by Vaibhavs10** [comment]
Thanks @chrisc36, do let me know if you need any help w/ that!

**Comment by jiasenlu** [comment]
Thanks, we are working on the Pytorch version, and the estimated release is in around 2 weeks.

**Comment by JVP15** [comment]
This is awesome work and I'd love to use it with my current HuggingFace setup! Is there any update on a Pytorch release?

**Comment by lukaemon** [comment]
> Thanks for the recommendation, we are working on a pytorch version which we plan to upload to huggingface.

Looking forward to the pytorch version. Thanks for the open source!

**Comment by jlgao23** [comment]
Looking forward to the pytorch version too.

**Comment by sangho-vision** [comment]
Hi all, the pytorch version is now ready: https://github.com/allenai/unified-io-2.pytorch

**Comment by lukaemon** [comment]
> Hi all, the pytorch version is now ready: https://github.com/allenai/unified-io-2.pytorch

Given 10m context window Gemini 1.5, Sora, V-JEPA and magic.dev all happening today, this is the best and most useful news to me. Thanks!
