### ISSUE TITLE
: Can you provide a usage guide? 

### ISSUE THREAD

**Issue by kelisiya** [allenai/unified-io-2#9]
Currently, there are too many buttons to upload, and whenever I select submit, it always tells me "image shape error".

**Comment by DeepJackNotFound** [comment]
Me too, Really need a uasge guide, i guess there is a Specified resolution of image needs to be upload. Or needs all of options to be upload.

**Comment by jiasenlu** [comment]
Sorry for the confusion, we will add a usage guide this weekend. and we are working on a PyTorch codebase that is easier for GPU and finetuning. Could you confirm what environment you are using? GPU or TPU?  @zcczhang can you in charge of that? Thanks!

**Comment by kelisiya** [comment]
i use A100&nbsp;



---Original---
From: "Jiasen ***@***.***&gt;
Date: Wed, Jan 24, 2024 08:32 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [allenai/unified-io-2] : Can you provide a usage guide?  (Issue#9)




 
Sorry for the confusion, we will add a usage guide this weekend. and we are working on a PyTorch codebase that is easier for GPU and finetuning. Could you confirm what environment you are using? GPU or TPU?

**Comment by zcczhang** [comment]
Hi @kelisiya and @DeepJackNotFound , Thanks for the interest! The error mostly came from the Gradio version updates and I just pushed the fix and the demo should work now. Please feel free to re-open the issue if there are any other related issues!

For the usage guide, we are now working on it, and will let you know when it's ready!
